Repository pfh59/eve-whmapper, pull requests merged in 2024-05, with the labels that each got.

#262 Enable selection box for all maps
  src/WHMapper/Pages/Mapper/Overview.razor
Labels: features, improvement, cla-signed

#264 multi fixes
  .github/workflows/ci-cd.yaml
  .gitignore
  src/WHMapper.Tests/WHMapper.Tests.csproj
  src/WHMapper/Models/Custom/Node/EveSystemNodeModel.cs
  src/WHMapper/Pages/Mapper/CustomNode/EveSystemNode.cs
  src/WHMapper/Pages/Mapper/CustomNode/EveSystemNode.razor
  src/WHMapper/Pages/Mapper/Overview.cs
  src/WHMapper/Pages/Mapper/Overview.razor
  src/WHMapper/Pages/Mapper/SystemInfos/Overview.cs
  src/WHMapper/Pages/Mapper/SystemInfos/Overview.razor
  src/WHMapper/Pages/_Layout.cshtml
  src/WHMapper/Program.cs
  src/WHMapper/Services/WHColor/WHColorHelper.cs
  src/WHMapper/WHMapper.csproj
  src/WHMapper/_Imports.razor
Labels: cla-signed

#265 reactivate sonarcloud
  .github/workflows/ci-cd.yaml
  src/WHMapper/_Imports.razor
Labels: CI, cla-signed

#267 Fix test
  src/WHMapper/Services/SDE/SDEServices.cs
Labels: bug, cla-signed

#268 Do not check floating point equality with exact values, use a range instead.
  src/WHMapper/Pages/Mapper/SystemInfos/Overview.cs
  src/WHMapper/Services/WHColor/WHColorHelper.cs
Labels: cla-signed

#269 Add test classes and add unit tests for AnoikServices
  src/WHMapper.Tests/AutoDomainDataAttribute.cs
  src/WHMapper.Tests/AutoMoqDataAttribute.cs
  src/WHMapper.Tests/DomainCustomization.cs
  src/WHMapper.Tests/InlineAutoMoqDataAttribute.cs
  src/WHMapper.Tests/Services/Anoik/AnoikServicesTests.cs
  src/WHMapper.Tests/WHMapper.Tests.csproj
  src/WHMapper/Services/Anoik/AnoikServices.cs
  src/WHMapper/Services/Anoik/IAnoikServices.cs
Labels: improvement, cla-signed
