Repository pfh59/eve-whmapper, pull requests merged in 2024-03, with the labels that each got.

#238 Update docker init.sh
  docker/init.sh
Labels: bug

#247 fix #242
  src/WHMapper/Pages/Mapper/Administration/Overview.cs
  src/WHMapper/Pages/Mapper/Administration/Overview.razor
Labels: bug, cla-signed

#248 fix #240
  src/WHMapper/Shared/MainLayout.razor
Labels: bug, cla-signed

#249 update CI
  .clabot
  .github/cla/signatures.json
  .github/workflows/ci-cd.yaml
  .github/workflows/cla.yml
  .github/workflows/publish-release.yml
  CLA.md
Labels: cla-signed

#250 Multi arch
  .github/workflows/ci-cd.yaml
  src/WHMapper/Dockerfile
Labels: CI, cla-signed

#252 Docker multi arch
  .github/workflows/ci-cd.yaml
Labels: cla-signed

#255 Multi deployment methods
  README.md
  deploy/docker/README.md
  deploy/docker/eve-whmapper/docker-compose.yml
  deploy/docker/haproxy/conf/haproxy.cfg
  deploy/docker/haproxy/docker-compose.yml
  deploy/docker/haproxy/nginx/nginx.conf
  deploy/docker/init.sh
  deploy/docker/renew-certificates.sh
  deploy/docker/start.sh
  deploy/docker/stop.sh
  deploy/kubernetes/README.md
  deploy/kubernetes/deploys/backend.yaml
  deploy/kubernetes/deploys/base.yaml
  deploy/kubernetes/deploys/envs.yaml
  deploy/kubernetes/deploys/frontend.yaml
  deploy/kubernetes/deploys/ingress.yaml
Labels: cla-signed

#254 FIX ASP.NET Core Runtime as Base for Multi platform
  src/WHMapper/Dockerfile
Labels: cla-signed

#256 ADD timestamp format for Console Message
  src/WHMapper/appsettings.json
Labels: cla-signed
