Repository pfh59/eve-whmapper, pull requests merged in 2024-06, with the labels that each got.

#270 AnoikService data supplier and unit tests
  src/WHMapper.Tests/Services/Anoik/AnoikDataSupplierTests.cs
  src/WHMapper.Tests/Services/Anoik/AnoikFromJSONFileTest.cs
  src/WHMapper.Tests/Services/Anoik/AnoikServiceTestConstants.cs
  src/WHMapper.Tests/Services/Anoik/AnoikServicesTests.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
  src/WHMapper.Tests/appsettings.json
  src/WHMapper/Program.cs
  src/WHMapper/Services/Anoik/AnoikJsonDataSupplier.cs
  src/WHMapper/Services/Anoik/AnoikServices.cs
  src/WHMapper/Services/Anoik/IAnoikDataSupplier.cs
  src/WHMapper/WHMapper.csproj
  src/WHMapper/appsettings.json
Labels: cla-signed

#271 Update ci-cd.yaml
  .github/workflows/ci-cd.yaml
Labels: CI, cla-signed

#274 add dependabot.yml file
  .github/dependabot.yml
Labels: CI, cla-signed

#277 FIX SDE import
  src/WHMapper.Tests/Models/Graph/GraphModelsTest.cs
  src/WHMapper/Services/SDE/SDEServices.cs
Labels: cla-signed

#279 Rework SDE Service to increase maintainability and testability
  src/WHMapper.Tests/Services/SDE/SDEUniverseTest.cs
  src/WHMapper.Tests/Services/SDE/SdeServiceManagerIntegrationTests.cs
  src/WHMapper.Tests/Services/SDE/SdeServicesTests.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperRoutePlannerHelperTest.cs
  src/WHMapper.Tests/WHMapper.Tests.csproj
  src/WHMapper.Tests/appsettings.json
  src/WHMapper/Program.cs
  src/WHMapper/Services/EveMapper/EveMapperHelper.cs
  src/WHMapper/Services/EveMapper/EveMapperRoutePlannerHelper.cs
  src/WHMapper/Services/EveMapper/EveMapperSearch.cs
  src/WHMapper/Services/SDE/ISDEDataSupplier.cs
  src/WHMapper/Services/SDE/ISDEService.cs
  src/WHMapper/Services/SDE/ISDEServiceManager.cs
  src/WHMapper/Services/SDE/ISDEServices.cs
  src/WHMapper/Services/SDE/SDEConstants.cs
  src/WHMapper/Services/SDE/SDEService.cs
  src/WHMapper/Services/SDE/SDEServiceManager.cs
  src/WHMapper/Services/SDE/SDEServices.cs
  src/WHMapper/Services/SDE/SdeDataSupplier.cs
  src/WHMapper/Shared/MainLayout.razor
  src/WHMapper/WHMapper.csproj
  src/WHMapper/appsettings.json
Labels: cla-signed

#278 First pass
  src/WHMapper.Tests/Models/Graph/GraphModelsTest.cs
  src/WHMapper.Tests/Services/Db/DbIntegrationTest.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
  src/WHMapper.Tests/WHHelper/WHColorHelperTest.cs
  src/WHMapper/Hubs/IWHMapperNotificationHub.cs
  src/WHMapper/Hubs/WHMapperNotificationHub.cs
  src/WHMapper/Models/Custom/Node/EveSystemNodeModel.cs
  src/WHMapper/Models/DTO/EveAPI/Assets/Asset.cs
  src/WHMapper/Models/DTO/EveMapper/Enums/EveSystemTypeEnums.cs
  src/WHMapper/Models/Db/Enums/WHSystemStatusEnums.cs
  src/WHMapper/Models/Db/WHNote.cs
  src/WHMapper/Pages/Mapper/Administration/Overview.cs
  src/WHMapper/Pages/Mapper/Notes/Overview.cs
  src/WHMapper/Pages/Mapper/Overview.cs
  src/WHMapper/Pages/Mapper/Overview.razor
  src/WHMapper/Pages/Mapper/RoutePlanner/Overview.cs
  src/WHMapper/Pages/Mapper/Signatures/Overview.cs
  src/WHMapper/Repositories/ADefaultRepository.cs
  src/WHMapper/Repositories/WHAccesses/WHAccessRepository.cs
  src/WHMapper/Repositories/WHAdmins/WHAdminRepository.cs
  src/WHMapper/Repositories/WHJumpLogs/WHJumpLogRepository.cs
  src/WHMapper/Repositories/WHMaps/WHMapRepository.cs
  src/WHMapper/Repositories/WHNotes/WHNoteRepository.cs
  src/WHMapper/Repositories/WHRoutes/WHRouteRepository.cs
  src/WHMapper/Repositories/WHSignatures/WHSignatureRepository.cs
  src/WHMapper/Repositories/WHSystemLinks/WHSystemLinkRepository.cs
  src/WHMapper/Repositories/WHSystems/WHSystemRepository.cs
  src/WHMapper/Services/EveMapper/EveMapperHelper.cs
  src/WHMapper/Services/EveMapper/EveMapperTracker.cs
  src/WHMapper/Services/EveMapper/IEveMapperHelper.cs
  src/WHMapper/Services/SDE/SDEServiceManager.cs
  src/WHMapper/Services/WHColor/IWHColorHelper.cs
  src/WHMapper/Services/WHColor/WHColorHelper.cs
  src/WHMapper/Services/WHSignatures/WHSignatureHelper.cs
Labels: improvement, cla-signed

#281 Optimization Reliability
  src/WHMapper/Pages/Mapper/Overview.cs
  src/WHMapper/Repositories/WHMaps/WHMapRepository.cs
  src/WHMapper/Repositories/WHRoutes/WHRouteRepository.cs
  src/WHMapper/Repositories/WHSignatures/WHSignatureRepository.cs
  src/WHMapper/Repositories/WHSystemLinks/WHSystemLinkRepository.cs
  src/WHMapper/Repositories/WHSystems/WHSystemRepository.cs
Labels: dev, improvement, cla-signed

#283 fix : #282
  src/WHMapper/Pages/Mapper/Overview.cs
Labels: bug, cla-signed

#284 Fix namespacing and write extra tests
  src/WHMapper.Tests/Services/EveApi/EveApiServicesTests.cs
  src/WHMapper.Tests/Services/EveOnlineAPI/PublicEveOnlineAPITest.cs
  src/WHMapper.Tests/WHHelper/EveWHAccessHelperTest.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperEntityTest.cs
  src/WHMapper.Tests/WHHelper/EveWHMapperHelperTest.cs
  src/WHMapper/Program.cs
  src/WHMapper/Services/EveAPI/Alliance/IAllianceServices.cs
  src/WHMapper/Services/EveAPI/Alliances/AllianceServices.cs
  src/WHMapper/Services/EveAPI/Alliances/IAllianceServices.cs
  src/WHMapper/Services/EveAPI/Character/CharacterServices.cs
  src/WHMapper/Services/EveAPI/Character/ICharacterServices.cs
  src/WHMapper/Services/EveAPI/Characters/CharacterServices.cs
  src/WHMapper/Services/EveAPI/Characters/ICharacterServices.cs
  src/WHMapper/Services/EveAPI/Corporation/CorporationServices.cs
  src/WHMapper/Services/EveAPI/Corporation/ICorporationServices.cs
  src/WHMapper/Services/EveAPI/Corporations/CorporationServices.cs
  src/WHMapper/Services/EveAPI/Corporations/ICorporationServices.cs
  src/WHMapper/Services/EveAPI/EveAPIServices.cs
  src/WHMapper/Services/EveAPI/EveApiServiceBase.cs
  src/WHMapper/Services/EveAPI/IEveAPIServices.cs
  src/WHMapper/Services/EveAPI/Locations/ILocationServices.cs
  src/WHMapper/Services/EveAPI/Locations/LocationServices.cs
  src/WHMapper/Services/EveAPI/Route/IRouteServices.cs
  src/WHMapper/Services/EveAPI/Route/RouteServices.cs
  src/WHMapper/Services/EveAPI/Routes/IRouteServices.cs
  src/WHMapper/Services/EveAPI/Routes/RouteServices.cs
  src/WHMapper/Services/EveMapper/EveMapperAccessHelper.cs
  src/WHMapper/Services/EveMapper/EveMapperRoutePlannerHelper.cs
  src/WHMapper/WHMapper.csproj
Labels: cla-signed
